# Generated by Django 2.0.5 on 2019-02-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
