# Generated by Django 2.0.5 on 2019-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobileno',
            field=models.CharField(help_text='enter your mobile number', max_length=10),
        ),
    ]
