# Generated by Django 2.0.5 on 2019-02-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190220_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year_of_study',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
