# Generated by Django 2.0.5 on 2019-02-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='cse', max_length=30),
        ),
    ]
