# Generated by Django 2.0.5 on 2019-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190220_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='event9',
            field=models.BooleanField(default=False),
        ),
    ]
