# Generated by Django 2.0.5 on 2019-02-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190225_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobileno',
            new_name='mobile_number',
        ),
    ]
