# Generated by Django 2.0.5 on 2019-03-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_event10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='collegename',
            new_name='college_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(max_length=12),
        ),
    ]
